/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaXO.java
 *
 * Created on 17/12/2012, 09:05:55
 */
package redesneurais;

import java.awt.Color;

/**
 *
 * @author Caio
 */
public class JanelaXO extends javax.swing.JFrame {

    /** Creates new form JanelaXO */
    public JanelaXO() {
        initComponents();
        jLabel2X.setVisible(false);
        jLabelO.setVisible(false);
        Color vermelho = new Color(255,0,0);
        Color preto = new Color(0,0,0);
        jCheckBox1.setSelected(true);
        jCheckBox1.setBackground(preto);
        jCheckBox2.setBackground(vermelho);
        jCheckBox3.setBackground(vermelho);
        jCheckBox4.setBackground(vermelho);
        jCheckBox5.setSelected(true);
        jCheckBox6.setBackground(vermelho);
        jCheckBox5.setBackground(preto);
        jCheckBox7.setSelected(true);
        jCheckBox7.setBackground(preto);
        jCheckBox8.setBackground(vermelho);
        jCheckBox9.setSelected(true);
        jCheckBox9.setBackground(preto);
        jCheckBox10.setBackground(vermelho);
        jCheckBox11.setBackground(vermelho);
        jCheckBox12.setBackground(vermelho);
        jCheckBox13.setSelected(true);
        jCheckBox13.setBackground(preto);
        jCheckBox14.setBackground(vermelho);
        jCheckBox15.setBackground(vermelho);
        jCheckBox16.setBackground(vermelho);
        jCheckBox17.setBackground(vermelho);
        jCheckBox18.setBackground(vermelho);
        jCheckBox19.setBackground(vermelho);
        jCheckBox20.setBackground(vermelho);
        jCheckBox21.setBackground(vermelho);
        jCheckBox22.setBackground(vermelho);
        jCheckBox23.setBackground(vermelho);
        jCheckBox24.setSelected(true);
        jCheckBox24.setBackground(preto);
        jCheckBox25.setSelected(true);
        jCheckBox25.setBackground(preto);
        jCheckBox17.setSelected(true);
        jCheckBox17.setBackground(preto);
        jCheckBox16.setSelected(true);
        jCheckBox16.setBackground(preto);
        
                                   

    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2X = new javax.swing.JLabel();
        jLabelO = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jCheckBox1.setActionCommand("jCheckBox1ActionPerformed");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setActionCommand("jCheckBox2ActionPerformed");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setActionCommand("jCheckBox3ActionPerformed");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setActionCommand("jCheckBox4ActionPerformed");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setActionCommand("jCheckBox5ActionPerformed");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setActionCommand("jCheckBox6ActionPerformed");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setActionCommand("jCheckBox7ActionPerformed");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setActionCommand("jCheckBox8ActionPerformed");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setActionCommand("jCheckBox9ActionPerformed");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox10.setActionCommand("jCheckBox10ActionPerformed");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jCheckBox11.setActionCommand("jCheckBox11ActionPerformed");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        jCheckBox12.setActionCommand("jCheckBox12ActionPerformed");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        jCheckBox13.setActionCommand("jCheckBox13ActionPerformed");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });

        jCheckBox14.setActionCommand("jCheckBox14ActionPerformed");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jCheckBox15.setActionCommand("jCheckBox15ActionPerformed");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });

        jCheckBox16.setActionCommand("jCheckBox16ActionPerformed");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });

        jCheckBox17.setActionCommand("jCheckBox17ActionPerformed");
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });

        jCheckBox18.setActionCommand("jCheckBox18ActionPerformed");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });

        jCheckBox19.setActionCommand("jCheckBox19ActionPerformed");
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
            }
        });

        jCheckBox20.setActionCommand("jCheckBox20ActionPerformed");
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });

        jCheckBox21.setActionCommand("jCheckBox24ActionPerformed");
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });

        jCheckBox22.setActionCommand("jCheckBox22ActionPerformed");
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });

        jCheckBox23.setActionCommand("jCheckBox23ActionPerformed");
        jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox23ActionPerformed(evt);
            }
        });

        jCheckBox24.setActionCommand("jCheckBox24ActionPerformed");
        jCheckBox24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox24ActionPerformed(evt);
            }
        });

        jCheckBox25.setActionCommand("jCheckBox25ActionPerformed");
        jCheckBox25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox25ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setText("Reconhecimento Carácters X e O via Regra de Hebb");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setText("Tabela");

        jLabel4.setText("Caio Eduardo Cunha Machado Caetano - 98090");

        jLabel5.setText("Polieny de Faria Albernaz  - 98109");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel3.setText("Modelos");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Resultado");

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("O");
        jButton2.setMaximumSize(new java.awt.Dimension(39, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(39, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel7.setText("Testar");

        jButton3.setText("Testar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redesneurais/LertaX.jpg"))); // NOI18N
        jLabel2X.setToolTipText("");
        jLabel2X.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2X.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2X.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabelO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redesneurais/o.jpg"))); // NOI18N
        jLabelO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelO.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jMenu1.setText("Modos");

        jMenuItem2.setText("Regra de Hebb");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Reconhecimento Carácters X e O");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenu2.addMenuDragMouseListener(new javax.swing.event.MenuDragMouseListener() {
            public void menuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {
                jMenu2MenuDragMouseEntered(evt);
            }
            public void menuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {
            }
        });

        jMenuItem1.setText("Projeto");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel3)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel7)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox15)
                            .addComponent(jCheckBox20)
                            .addComponent(jCheckBox25))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox11)
                            .addComponent(jCheckBox16)
                            .addComponent(jCheckBox21))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox13)
                            .addComponent(jCheckBox18)
                            .addComponent(jCheckBox23))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox12)
                            .addComponent(jCheckBox17)
                            .addComponent(jCheckBox22))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox10)
                            .addComponent(jCheckBox14)
                            .addComponent(jCheckBox19)
                            .addComponent(jCheckBox24))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelO)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2X))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addComponent(jCheckBox6)
                        .addComponent(jCheckBox15)
                        .addComponent(jCheckBox20)
                        .addComponent(jCheckBox25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addComponent(jCheckBox7)
                        .addComponent(jCheckBox11)
                        .addComponent(jCheckBox16)
                        .addComponent(jCheckBox21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox3)
                        .addComponent(jCheckBox8)
                        .addComponent(jCheckBox13)
                        .addComponent(jCheckBox18)
                        .addComponent(jCheckBox23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox4)
                        .addComponent(jCheckBox9)
                        .addComponent(jCheckBox12)
                        .addComponent(jCheckBox17)
                        .addComponent(jCheckBox22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox5)
                        .addComponent(jCheckBox10)
                        .addComponent(jCheckBox14)
                        .addComponent(jCheckBox19)
                        .addComponent(jCheckBox24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelO))
                    .addComponent(jLabel2X))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jLabel5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
         Color preto = new Color(0,0,0);
         Color vermelho = new Color(255,0,0);
         
         boolean state = jCheckBox1.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox1.setBackground(preto); 
           else
                 jCheckBox1.setBackground(vermelho); 
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code hColor preto = new Color(255,0,0);
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox2.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox2.setBackground(preto); 
           else
                 jCheckBox2.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox11.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox11.setBackground(preto); 
           else
                 jCheckBox11.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox15.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox15.setBackground(preto); 
           else
                 jCheckBox15.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox16.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox16.setBackground(preto); 
           else
                 jCheckBox16.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox20.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox20.setBackground(preto); 
           else
                 jCheckBox20.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox21ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox21.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox21.setBackground(preto); 
           else
                 jCheckBox21.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox21ActionPerformed

    private void jCheckBox25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox25ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox25.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox25.setBackground(preto); 
           else
                 jCheckBox25.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox25ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
        Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox6.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox6.setBackground(preto); 
           else
                 jCheckBox6.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox14.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox14.setBackground(preto); 
           else
                 jCheckBox14.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox9.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox9.setBackground(preto); 
           else
                 jCheckBox9.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox3.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox3.setBackground(preto); 
           else
                 jCheckBox3.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox4.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox4.setBackground(preto); 
           else
                 jCheckBox4.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox5.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox5.setBackground(preto); 
           else
                 jCheckBox5.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox7.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox7.setBackground(preto); 
           else
                 jCheckBox7.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox8.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox8.setBackground(preto); 
           else
                 jCheckBox8.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox10.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox10.setBackground(preto); 
           else
                 jCheckBox10.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox13.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox13.setBackground(preto); 
           else
                 jCheckBox13.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox12.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox12.setBackground(preto); 
           else
                 jCheckBox12.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox18.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox18.setBackground(preto); 
           else
                 jCheckBox18.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox17.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox17.setBackground(preto); 
           else
                 jCheckBox17.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox19ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox19.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox19.setBackground(preto); 
           else
                 jCheckBox19.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox19ActionPerformed

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox22.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox22.setBackground(preto); 
           else
                 jCheckBox22.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox23ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox23.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox23.setBackground(preto); 
           else
                 jCheckBox23.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox23ActionPerformed

    private void jCheckBox24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox24ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
         Color preto = new Color(0,0,0);
         
         boolean state = jCheckBox24.isSelected();
 //Set JCheckBox background color to color that you choose  
           if(state)
                jCheckBox24.setBackground(preto); 
           else
                 jCheckBox24.setBackground(vermelho);
    }//GEN-LAST:event_jCheckBox24ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Color vermelho = new Color(255,0,0);
        Color preto = new Color(0,0,0);
        jCheckBox1.setSelected(true);
        jCheckBox1.setBackground(preto);
        jCheckBox2.setBackground(vermelho);
        jCheckBox2.setSelected(false);
        jCheckBox3.setBackground(vermelho);
        jCheckBox3.setSelected(false);
        jCheckBox4.setBackground(vermelho);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(true);
        jCheckBox6.setBackground(vermelho);
        jCheckBox5.setBackground(preto);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(true);
        jCheckBox7.setBackground(preto);
        jCheckBox8.setSelected(false);
        jCheckBox8.setBackground(vermelho);
        jCheckBox9.setSelected(true);
        jCheckBox9.setBackground(preto);
        jCheckBox10.setSelected(false);
        jCheckBox10.setBackground(vermelho);
        jCheckBox11.setSelected(false);
        jCheckBox11.setBackground(vermelho);
        jCheckBox12.setSelected(false);
        jCheckBox12.setBackground(vermelho);
        jCheckBox13.setSelected(true);
        jCheckBox13.setBackground(preto);
        jCheckBox14.setSelected(false);
        jCheckBox14.setBackground(vermelho);
        jCheckBox15.setSelected(false);
        jCheckBox15.setBackground(vermelho);
        jCheckBox16.setSelected(false);
        jCheckBox16.setBackground(vermelho);
        jCheckBox17.setSelected(false);
        jCheckBox17.setBackground(vermelho);
        jCheckBox18.setSelected(false);
        jCheckBox18.setBackground(vermelho);
        jCheckBox19.setSelected(false);
        jCheckBox19.setBackground(vermelho);
        jCheckBox20.setSelected(false);
        jCheckBox20.setBackground(vermelho);
        jCheckBox21.setSelected(false);
        jCheckBox21.setBackground(vermelho);
        jCheckBox22.setSelected(false);
        jCheckBox22.setBackground(vermelho);
        jCheckBox23.setSelected(false);
        jCheckBox23.setBackground(vermelho);
        jCheckBox24.setSelected(true);
        jCheckBox24.setBackground(preto);
        jCheckBox25.setSelected(true);
        jCheckBox25.setBackground(preto);
        jCheckBox17.setSelected(true);
        jCheckBox17.setBackground(preto);
        jCheckBox16.setSelected(true);
        jCheckBox16.setBackground(preto);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Color vermelho = new Color(255,0,0);
        Color preto = new Color(0,0,0);
        jCheckBox1.setSelected(false);
        jCheckBox1.setBackground(vermelho);
        jCheckBox2.setBackground(preto);
        jCheckBox2.setSelected(true);
        jCheckBox3.setBackground(preto);
        jCheckBox3.setSelected(true);
        jCheckBox4.setBackground(preto);
        jCheckBox4.setSelected(true);
        jCheckBox5.setSelected(false);
        jCheckBox6.setBackground(preto);
        jCheckBox5.setBackground(vermelho);
        jCheckBox6.setSelected(true);
        jCheckBox7.setSelected(false);
        jCheckBox7.setBackground(vermelho);
        jCheckBox8.setSelected(false);
        jCheckBox8.setBackground(vermelho);
        jCheckBox9.setSelected(false);
        jCheckBox9.setBackground(vermelho);
        jCheckBox10.setSelected(true);
        jCheckBox10.setBackground(preto);
        jCheckBox11.setSelected(false);
        jCheckBox11.setBackground(vermelho);
        jCheckBox12.setSelected(false);
        jCheckBox12.setBackground(vermelho);
        jCheckBox13.setSelected(false);
        jCheckBox13.setBackground(vermelho);
        jCheckBox14.setSelected(true);
        jCheckBox14.setBackground(preto);
        jCheckBox15.setSelected(true);
        jCheckBox15.setBackground(preto);
        jCheckBox16.setSelected(false);
        jCheckBox16.setBackground(vermelho);
        jCheckBox17.setSelected(false);
        jCheckBox17.setBackground(vermelho);
        jCheckBox18.setSelected(false);
        jCheckBox18.setBackground(vermelho);
        jCheckBox19.setSelected(true);
        jCheckBox19.setBackground(preto);
        jCheckBox20.setSelected(true);
        jCheckBox20.setBackground(preto);
        jCheckBox21.setSelected(true);
        jCheckBox21.setBackground(preto);
        jCheckBox22.setSelected(true);
        jCheckBox22.setBackground(preto);
        jCheckBox23.setSelected(true);
        jCheckBox23.setBackground(preto);
        jCheckBox24.setSelected(false);
        jCheckBox24.setBackground(vermelho);
        jCheckBox25.setSelected(false);
        jCheckBox25.setBackground(vermelho);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        int x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25;
        int t, b = 0, y=0;
        int w1, w2, w3, w4, w5, w6 ,w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25;
        try {
            
                x1=1;
                x2=-1;
                x3=-1;
                x4=-1;
                x5=1;
                x6=-1;
                x7=1;
                x8=-1;
                x9=1;
                x10=-1;
                x11=-1;
                x12=-1;
                x13=1;
                x14=-1;
                x15=-1;
                x16=-1;
                x17=1;
                x18=-1;
                x19=1;
                x20=-1;
                x21=1;
                x22=-1;
                x23=-1;
                x24=-1;
                x25=1;
                     
                
                
                t = 1;  
                w1=x1*t;
                w2=x2*t;
                w3=x3*t;
                w4=x4*t;
                w5=x5*t;
                w6=x6*t;
                w7=x7*t;
                w8=x8*t;
                w9=x9*t;
                w10=x10*t;
                w11=x11*t;
                w12=x12*t;
                w13=x13*t;
                w14=x14*t;
                w15=x15*t;
                w16=x16*t;
                w17=x17*t;
                w18=x18*t;
                w19=x19*t;
                w20=x20*t;
                w21=x21*t;
                w22=x22*t;
                w23=x23*t;
                w24=x24*t;
                w25=x25*t;
                                
                b += t;   
            
            
                x1=-1;
                x2=1;
                x3=1;
                x4=1;
                x5=-1;
                x6=1;
                x7=-1;
                x8=-1;
                x9=-1;
                x10=1;
                x11=1;
                x12=-1;
                x13=-1;
                x14=-1;
                x15=1;
                x16=1;
                x17=-1;
                x18=-1;
                x19=-1;
                x20=1;
                x21=-1;
                x22=1;
                x23=1;
                x24=1;
                x25=-1;
                     
                t = -1;  
                w1+=x1*t;
                w2+=x2*t;
                w3+=x3*t;
                w4+=x4*t;
                w5+=x5*t;
                w6+=x6*t;
                w7+=x7*t;
                w8+=x8*t;
                w9+=x9*t;
                w10+=x10*t;
                w11+=x11*t;
                w12+=x12*t;
                w13+=x13*t;
                w14+=x14*t;
                w15+=x15*t;
                w16+=x16*t;
                w17+=x17*t;
                w18+=x18*t;
                w19+=x19*t;
                w20+=x20*t;
                w21+=x21*t;
                w22+=x22*t;
                w23+=x23*t;
                w24+=x24*t;
                w25+=x25*t;
                                
                b += t;  
           
              
            
            if(jCheckBox1.isSelected())
                x1 = 1; 
            else
                x1 = -1;
            if(jCheckBox2.isSelected())
                x2 = 1; 
            else
                x2 = -1;
            if(jCheckBox3.isSelected())
                x3 = 1; 
            else
                x3 = -1;
            if(jCheckBox4.isSelected())
                x4 = 1; 
            else
                x4 = -1;
            if(jCheckBox5.isSelected())
                x5 = 1; 
            else
                x5 = -1;
            if(jCheckBox6.isSelected())
                x6 = 1; 
            else
                x6 = -1;
            if(jCheckBox7.isSelected())
                x7 = 1; 
            else
                x7 = -1;
            if(jCheckBox8.isSelected())
                x8 = 1; 
            else
                x8 = -1;
            if(jCheckBox9.isSelected())
                x9 = 1; 
            else
                x9 = -1;
            if(jCheckBox10.isSelected())
                x10 = 1; 
            else
                x10 = -1;
            if(jCheckBox15.isSelected())
                x11 = 1; 
            else
                x11 = -1;
            if(jCheckBox11.isSelected())
                x12 = 1; 
            else
                x12 = -1;
            if(jCheckBox13.isSelected())
                x13 = 1; 
            else
                x13 = -1;
            if(jCheckBox12.isSelected())
                x14 = 1; 
            else
                x14 = -1;
            if(jCheckBox14.isSelected())
                x15 = 1; 
            else
                x15 = -1;
            if(jCheckBox20.isSelected())
                x16 = 1; 
            else
                x16 = -1;
            if(jCheckBox16.isSelected())
                x17 = 1; 
            else
                x17 = -1;
            if(jCheckBox18.isSelected())
                x18 = 1; 
            else
                x18 = -1;
            if(jCheckBox17.isSelected())
                x19 = 1; 
            else
                x19 = -1;
            if(jCheckBox19.isSelected())
                x20 = 1; 
            else
                x20 = -1;
            if(jCheckBox25.isSelected())
                x21 = 1; 
            else
                x21 = -1;
            if(jCheckBox21.isSelected())
                x22 = 1; 
            else
                x22 = -1;
            if(jCheckBox23.isSelected())
                x23 = 1; 
            else
                x23 = -1;
            if(jCheckBox22.isSelected())
                x24 = 1; 
            else
                x24 = -1;
            if(jCheckBox24.isSelected())
                x25 = 1; 
            else
                x25 = -1; 
            
            
            y = x1*w1 +
                    x2*w2 +
                    x3*w3 +
                    x4*w4 +
                    x5*w5 +
                    x6*w6 +
                    x7*w7 +
                    x8*w8 +
                    x9*w9 +
                    x10*w10 +
                    x11*w11+
                    x12*w12 +
                    x13*w13 +
                    x14*w14 +
                    x15*w15 +
                    x16*w16 +
                    x17*w17 +
                    x18*w18 +
                    x19*w19 +
                    x20*w20 +
                    x21*w21 +
                    x22*w22 +
                    x23*w23 +
                    x24*w24 +
                    x25*w25 +
                    b;
            
                      
            if(y>=0){
                jLabel2X.setVisible(true);
                jLabelO.setVisible(false);
            }else{
                jLabel2X.setVisible(false);
                jLabelO.setVisible(true);
            }
            
            
            }catch (Exception e) {}  
                    
              
                    
                    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenu2MenuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_jMenu2MenuDragMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2MenuDragMouseEntered

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        // TODO add your handling code here:        
        RedesNeurais.getHebb().setVisible(true);
        RedesNeurais.getXO().setVisible(false);
        
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, "Projeto de Inteligência Artificial\n Prof. Keiji Yamanaka\n Parte 1- Regra de Hebb (13/12/12)\n Parte 2 - Reconhecimento de Carácters X e O(18/12/12)\n\n Autores:\nCaio Eduardo Cunha Machado Caetano - 98090\n Polieny de Faria Albernaz - 98109\n");
    
    }//GEN-LAST:event_jMenuItem1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaXO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaXO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaXO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaXO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JanelaXO().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2X;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelO;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
